gadgets/urls.py
from django.urls import path
from .import views
app_name='gadgets'


urlpatterns=[

    path('gadget',views.gadgets, name='gadgets'),

     path('gadget',views.gadgets, name='baabtra'),

      path('gadget',views.gadgets, name='about'),

       path('gadget',views.gadgets, name='baabtra')



    
 
]

home/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mycart/',include('mycart.urls')),
    path('gadgets/',include('gadgets.urls'))
]

mycart/urls.py
from django.urls import path
from .import views

app_name='mycart'
urlpatterns=[

    path('index',views.index),
    path('home',views.home),
    path('face',views.face),
    path('baabtra',views.baabtra,name='baabtraname' ),
    path('about',views.about,name='aboutname'),
    path('contact',views.contact,name='contactname'),
    path('viewpage',views.viewpage,name='toviewpage')

]

baabtra/models.py
from django.db import models

# Create your models here.

gadgets/models.py
from django.db import models

# Create your models here.

mycart/models.py
from django.db import models

# Create your models here.

baabtra/views.py
from django.shortcuts import render

# Create your views here.

gadgets/views.py
from django.shortcuts import render

# Create your views here.

def gadgets(request):
    return render(request,"gadgets/gadgets.html")

def gadgets(request):
    return render(request,"gadgets/baabtra.html")

def gadgets(request):
    return render(request,"gadgets/about.html")

def gadgets(request):
    return render(request,"gadgets/contact.html")

mycart/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request,"mycart/index.html")

def home(request):
    return HttpResponse('welcome')

def face(request):
    return render(request,"mycart/face.html")

def baabtra(request):
    return render(request,"mycart/baabtra.html")


def about(request):
    return render(request,"mycart/about.html")


def contact(request):
    return render(request,"mycart/contact.html")


def viewpage(request):
    return render(request,"mycart/viewpage.html")

gadgets/templates/gadgets/gadgets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <a href="[% url]'myapp:gadgets'">homepage</a>
   <a href="">about baabtra</a>
   <a href="">contact</a>
    <h1>gadsets</h1>
    
</body>
</html>

mycart/templates/mycart/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img src="{% static 'images/download(1).jfif'}" alt="">
    <table  width="50%" align="CENTER" >
        <tr><th colspan="3">BAABTRA <BR></BR></th></tr>
        <TR align="center"><td>
            <a href="./HOME.HTML">HOME</a></td>
        <td>
        <a href="./about.html">ABOUT
        </td>
        </a>
        <td>
            <a href="./contact.html">CONTACT</a>
        </td>
        </TR>
        
        
       
        </table>
    <h1 align="center">BAABTRA</h1>
    <p>LEARN SOFTWARE
        Getting a Software Job is So Easy Now with our IT Internship Programs.
        Learn programming from Kerala's most trusted software training company with the highest placement record. Enroll in software courses and internship programs in Python, Flutter, Angular, React and PHP to start your career.</p>


    <p>EXPLORE OUR INTERNSHIP PROGRAMME
        Learn new skills to go ahead of your career
        Join Us
        It doesn’t matter how talented you are. Join specialized job oriented software courses & training programs and just learn the in-demand skills to be a better programmer.
        
        Get Skilled for Job
        Get trained and skilled under the guidance of expert software engineers and be ready for the jobs.
        
        Get Hired
        Showcase your profile with skills acquired and get hired by your dream company.</p>
        <img src="./pic.jpeg" alt="" height="500" width="500">
        <img src="./pic1.jpg" alt="" height="500" width="500">
</body>
</html>

mycart/templates/mycart/baabtra.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img src="{% static 'image/download.png' %}" alt="">
    <a href="{% url 'mycart:baabtraname' %}">baabtra</a>
    <a href="{% url 'mycart:aboutname' %}">about</a>
    <a href="{% url 'mycart:contactname' %}">contact</a>
<table  width="50%" align="CENTER" >
<tr><th colspan="3">BAABTRA <BR></BR></th></tr>
<TR align="center"><td>
    <a href="./index.html">HOME</a></td>
<td>
<a href="./about.html">ABOUT
</td>
</a>
<td>
    <a href="./contact.html">CONTACT</a>
</td>
</TR>



</table>
<H1 ALIGN="CENTER">COURSES PROVIDED</H1>
<UL ALIGN="CENTER">
    <li>PYTHON</li>
    <img src="./download (1).jfif" alt="" height="55" width="55" align="">
    <LI>JAVA</LI>
    <img src="./download.png" alt="" height="80" width="100">
    <LI>C++</LI>
    <img src="./cpp.png" alt="" height="55" width="55">
    <LI>PHP</LI>
    <img src="./php.png" alt="" height="55" width="55">
</UL>

</body>
</html>

mycart/templates/mycart/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <hr>
<h1>this is header</h1>
    </div>
{% block homepage %} 
{% endblock %}
<h1>homepage</h1>
<div>
    <hr>
    <h1>this is footer</h1>
</div>
</body>
</html>

mycart/templates/mycart/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem ipsum veniam ullam mollitia ipsam exercitationem consequatur esse et debitis! Quaerat architecto dignissimos earum minus odit, cumque nulla voluptatem beatae praesentium.</p>
<table  width="50%" align="CENTER" >
    <tr><th colspan="3">BAABTRA <BR></BR></th></tr>
    <TR align="center"><td>
        <a href="./index.html">HOME</a></td>
    <td>
    <a href="./about.html">ABOUT
    </td>
    </a>
    <td>
        <a href="./contact.html">CONTACT</a>
    </td>
    </TR>
    
    
    
    </table>
    <br><br><br><br><br><br><br>
    <h1 align="center"> CONTACT</h1>
    <P ALIGN="CENTER">
        +91 859 205 8444 <BR></BR>
        info@baabtra.com <BR></BR>
        CAFIT Square, 5th Floor, HiLite Business Park, Thondayad Bye-Pass, Hilite City, Calicut, Kerala, India.
        </P>
</body>
</html>

mycart/templates/mycart/face.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 >facebook</h1>
</body>
</html>

mycart/templates/mycart/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>my cart</h1>
</body>
</html>

mycart/templates/mycart/viewpage.html
{% extends 'mycart/base.html' %}